//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba5.Models
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentEvent", Namespace="http://schemas.datacontract.org/2004/07/Laba5.Models")]
    public partial class StudentEvent : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateField;
        
        private string DescriptionField;
        
        private int IdField;
        
        private string LocationField;
        
        private string OrganizerField;
        
        private string TitleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Organizer
        {
            get
            {
                return this.OrganizerField;
            }
            set
            {
                this.OrganizerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IEventsServiceWCF")]
public interface IEventsServiceWCF
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventsServiceWCF/GetEventsByDate", ReplyAction="http://tempuri.org/IEventsServiceWCF/GetEventsByDateResponse")]
    Laba5.Models.StudentEvent[] GetEventsByDate(string date);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventsServiceWCF/GetEventsByDate", ReplyAction="http://tempuri.org/IEventsServiceWCF/GetEventsByDateResponse")]
    System.Threading.Tasks.Task<Laba5.Models.StudentEvent[]> GetEventsByDateAsync(string date);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventsServiceWCF/GetAllEvents", ReplyAction="http://tempuri.org/IEventsServiceWCF/GetAllEventsResponse")]
    Laba5.Models.StudentEvent[] GetAllEvents();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventsServiceWCF/GetAllEvents", ReplyAction="http://tempuri.org/IEventsServiceWCF/GetAllEventsResponse")]
    System.Threading.Tasks.Task<Laba5.Models.StudentEvent[]> GetAllEventsAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IEventsServiceWCFChannel : IEventsServiceWCF, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class EventsServiceWCFClient : System.ServiceModel.ClientBase<IEventsServiceWCF>, IEventsServiceWCF
{
    
    public EventsServiceWCFClient()
    {
    }
    
    public EventsServiceWCFClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public EventsServiceWCFClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EventsServiceWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EventsServiceWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Laba5.Models.StudentEvent[] GetEventsByDate(string date)
    {
        return base.Channel.GetEventsByDate(date);
    }
    
    public System.Threading.Tasks.Task<Laba5.Models.StudentEvent[]> GetEventsByDateAsync(string date)
    {
        return base.Channel.GetEventsByDateAsync(date);
    }
    
    public Laba5.Models.StudentEvent[] GetAllEvents()
    {
        return base.Channel.GetAllEvents();
    }
    
    public System.Threading.Tasks.Task<Laba5.Models.StudentEvent[]> GetAllEventsAsync()
    {
        return base.Channel.GetAllEventsAsync();
    }
}
